# Generated by Django 3.1.4 on 2021-01-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200131_0131'),
        ('todo', '0002_auto_20210120_1905'),
    ]

    operations = [
    ]
